### PR TITLE
chore(#652): seeing if setting the time helps

### LINKED ISSUE #652: Fix Flaky Test: user_can_create_booking_request - Tests.Feature.BookingRequestControllerTest
## Current Behavior

image

## Steps to Reproduce

https://app.circleci.com/pipelines/github/CSU-Booking-Platform/application/1742/workflows/22880b2b-8d34-4443-8414-b836b5752c82/jobs/5657/tests#failed-test-0

## Context (Environment)

# Bug Submission Checklist
- [ ] Replication steps
- [ ] Screenshots
- [ ] Tagged commits fixing the bug for traceability
- [ ] Tagged commits updating tests to cover the reported bug	
- [ ] (optional) tagged with “performance” label if performance related

### PR DESCRIPTION
**Pull request by EvanDime**
##### _What existing problem does the pull request solve?_

Looking into why this test is flacky on CI environment
##### _List all issues this PR resolves_
- closes #652

##### _Complete these items before requesting reviews_
- [x] Static Analysis Rules Validated
- [x] All commits follow naming conventions

### CODE REVIEW

**Review by alexstojda — APPROVED** [review]
🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 

In place of a meaningful review, take these rockets

**Review by Alex-Hayeur — APPROVED** [review]
There's no fingers-crossed emoji on Github. So good luck

**Review by a-drew — APPROVED** [review]
only magic can defeat magic

**Review by alexstojda — APPROVED** [review]
🥇

**Pull request merged**
