### PR TITLE
task(#657): fixed modal scroll issue

### LINKED ISSUE #657: Correct scroll issue in modals
### What needs to be done
 
Users are unable to scroll when a modal is open, and view the rest of its contents if it extends longer than the page. 

Probably can be fixed by adding `overflow-y-scroll` to the modal portal div

### LINKED ISSUE #664: fix Z-index on user icons in booking reviews list
### What needs to be done
 
image

Remove the `z-30` class from the User icon to fix this display issue when the modal is open

### LINKED ISSUE #666: My Bookings filter UI improvements
### What needs to be done
 
Improve the UI of the My Bookings filter modal to match the others 
image
image

### PR DESCRIPTION
**Pull request by jonathanp16**
##### _What existing problem does the pull request solve?_
Modal scroll issue, zindex, changed date input to datepicker

image
image

##### _List all issues this PR resolves_
- closes #657 
- closes #666
- closes #664 

##### _Complete these items before requesting reviews_
- [x] Static Analysis Rules Validated
- [x] All commits follow naming conventions

### Sub-tasks Checklist
- [x] UI Implementation
- [ ] UI Test
- [ ] Backend Implementation
- [ ] Backend Tests
- [ ] Integration Tests
- [ ] System Tests
- [ ] Documentation

### CODE REVIEW

**Review by danseremet — DISMISSED** [review]
I tested this locally, I see it working perfectly. Nice job! :100: 
ViewDetails
CalendarDate

**Review by alexstojda — CHANGES_REQUESTED** [review]
Your description closes 3 tickets, but I only see one commit ?

**Comment by jonathanp16** [comment]
> Your description closes 3 tickets, but I only see one commit ?

Put the wrong issue number

**Comment by jonathanp16** [comment]
> Your description closes 3 tickets, but I only see one commit ?

Also fixed all 3 issues in one commit since they were really small... probably should have done atomic commits but they were one-liners

**Review by EvanDime — APPROVED** [review]
shame we need to set the height for this to work. but i do approve of the fix. We get the results we want

**Review by a-drew — APPROVED** [review]

**Review by a-drew — DISMISSED** [review]
3 in one

**Review by EvanDime — DISMISSED** [review]

**Review by a-drew — APPROVED** [review]

**Review by alexstojda — APPROVED** [review]
yeet 🚀

**Review by danseremet — APPROVED** [review]
already approved :rocket:

**Pull request merged**
