### PR TITLE
fix(#459): Fix CI

### LINKED ISSUE #459: PHP Test Failing due to XDebug Mode
## Current Behavior

CI crashes at php-test due to the xdebug mode

image

## Possible Solution
Rebake proj image

## Steps to Reproduce

Check PR  #452 
https://app.circleci.com/pipelines/github/CSU-Booking-Platform/application/1020/workflows/65bc7555-1ae8-4e73-b5a5-642ab811e4a2/jobs/2212

## Context (Environment)

# Bug Submission Checklist
- [x] Replication steps
- [x] Screenshots
- [x] Tagged commits fixing the bug for traceability
- [ ] Tagged commits updating tests to cover the reported bug	
- [ ] (optional) tagged with “performance” label if performance related

### PR DESCRIPTION
**Pull request by alexstojda**
##### _List all issues this PR resolves_
- closes #459

Blocked by https://github.com/CSU-Booking-Platform/container-spec/pull/10

##### _Complete these items before requesting reviews_
- [x] Static Analysis Rules Validated
- [x] All commits follow naming conventions

### CODE REVIEW

**Review by WindOfRussia — DISMISSED** [review]
Noticed you pulled out chrome from the install. I assume you baked it into the image?

**Comment by EvanDime** [comment]
@alexstojda There still seems to be issues with the build. Do you need any help to get this merge through?

**Review by EvanDime — APPROVED** [review]
Perfect! Glad we have a good CI pipeline again!

**Comment by alexstojda** [comment]
> Perfect! Glad we have a good CI pipeline again!

Me too, were there any changes in the code you wanted to discuss? Or did everything look ok to you?

**Comment by WindOfRussia** [comment]
> > Perfect! Glad we have a good CI pipeline again!
> 
> Me too, were there any changes in the code you wanted to discuss? Or did everything look ok to you?

I think the changes are fine. makes sense to setup chrome directly in the image and to validate commit messages for forks and dependabot.

**Pull request merged**
