### PR TITLE
482 calendar

### LINKED ISSUE #482: As a user, I want to see a monthly calendar to view room availabilities.
### User story
As a user, I want to see a monthly calendar to view room availabilities.

### Narrative
Users want to see a monthly calendar to see room availabilities.
On each day of the month, there are boxed lines to indicate bookings of that room on that day.
The user can click on the day to view the day in detail (dates booked).

### Acceptance criteria

#580

### PR DESCRIPTION
**Pull request by jonathanp16**
##### _What existing problem does the pull request solve?_
Add a calendar Gantt-styled view of all the rooms and their availabilities. Can bump the calendar left or right by an hour, moving the hour range for all rooms. 

Black -> blackout/unavailable
Red -> booked
Green -> available to be booked

image

##### _List all issues this PR resolves_
- closes #482 

##### _Complete these items before requesting reviews_
- [x] Static Analysis Rules Validated
- [x] All commits follow naming conventions

### Sub-tasks Checklist
- [x] UI Implementation
- [x] UI Test
- [x] Backend Implementation
- [x] Backend Tests
- [ ] Integration Tests
- [ ] System Tests
- [x] Documentation

### CODE REVIEW

**Review by alecadub — APPROVED** [review]
I've been working on the feature with you using the codeWithMe extension !!! It's good to go :)

**Review by a-drew — DISMISSED** [review]
very calandar, such gantt 🥳 🍾

**Review by a-drew — APPROVED** [review]
That 96.3% coverage 😍 

<a href="https://imgflip.com/i/54dp67"></a>

**Review by alecadub — APPROVED** [review]
SHIP IT!

**Pull request merged**
