### PR TITLE
Send button and form UI fixes

### LINKED ISSUE #605: Improve UX of review comments
1. If you are on a small screen, the bubble of the user gets squished (if the comment is extra large). 

image

2. The whole page get's refreshed after you send a comment, It shouldn't do that. Also, the rich text editor is still filled with the same value you just sended.

image

3. At the same time, use moment to format the time at the top of the booking page

image

### What needs to be done
 

1. Clear the rich text editor after sending the request
2. Add a max-width to the div that display comments
3. Fix reload/scroll up to the top of page after sending comment

### LINKED ISSUE #663: Send button is not user-friendly for submitting comments on a booking
### What needs to be done
 
The submit comment button is not user-friendly for submitting comments:

image

Add a "submit comment" button in the same style as the other forms, under the text field (indicated in green) and remove the old button

### LINKED ISSUE #673: Bookings Description settings don't work
## Expected Behavior

Bookings Description settings form should update the settings

## Current Behavior

Nothing happens, the form does not submit. 

Errors are thrown in the console

## Steps to Reproduce

1. Go to /admin/settings
2. Try to modify Bookings Description settings
3. See console for errors.

## Context (Environment)

# Bug Submission Checklist
- [ ] Replication steps
- [ ] Screenshots
- [ ] Tagged commits fixing the bug for traceability
- [ ] Tagged commits updating tests to cover the reported bug	
- [ ] (optional) tagged with “performance” label if performance related

### PR DESCRIPTION
**Pull request by KeeganWoods1**
##### _What existing problem does the pull request solve?_

Fixes to the comments UX as well as the text box submit button.

Screenshot 2021-04-10 2144323

dfrgbds

##### _List all issues this PR resolves_
- closes #605, 
- closes #663
- closes #673

##### _Complete these items before requesting reviews_
- [ ] Static Analysis Rules Validated
- [ ] All commits follow naming conventions

### Sub-tasks Checklist
- [ ] UI Implementation
- [ ] UI Test
- [ ] Backend Implementation
- [ ] Backend Tests
- [ ] Integration Tests
- [ ] System Tests
- [ ] Documentation

### CODE REVIEW

**Review by Alex-Hayeur — APPROVED** [review]
Good job, the button matches with the rest of the site and the UX features like preserving the scroll instead of the state now will make it a lot less clunky to use.

**Comment by alexstojda** [comment]
@KeeganWoods1 I noticed the submit function for the admin settings that you modified with the new button, is actually broken on main. Did you by chance fix that in this PR? 

If so we can close https://github.com/CSU-Booking-Platform/application/issues/673

**Comment by KeeganWoods1** [comment]
> @KeeganWoods1 I noticed the submit function for the admin settings that you modified with the new button, is actually broken on main. Did you by chance fix that in this PR?
> 
> If so we can close #673

Just tried, I have indeed fixed this! We can close #673.

**Review by alexstojda — APPROVED** [review]
LGTM! Also updated the PR description to close #673 

CC: @alecadub

**Pull request merged**
