### PR TITLE
doc: add sub-task to PR TEMPLATE

### PR DESCRIPTION
**Pull request by danseremet**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**
Please provide enough information so that others can review your pull request:

Explain the **details** for making this change. What existing problem does the pull request solve?

### Test plan (required)
Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

### Closing issues
List all issues this PR resolves.
- `closes #XXXX` 

### Pre-Merge checklist 
Complete these items before requesting reviews
- [ ] Static Analysis Rules Validated
- [ ] All commits follow naming conventions

### CODE REVIEW

**Comment by danseremet** [comment]
I think it needs the dependabot bump issue before since I merged it in my fork..

**Review by EvanDime — COMMENTED** [review]
Why are there changes to the composer.lock file for this update?

**Review by alexstojda — CHANGES_REQUESTED** [review]
please remove composer.lock changes since they are not pertinent to this PR

**Review by alexstojda — APPROVED** [review]
This will be very helpful :)

**Review by WindOfRussia — APPROVED** [review]
Approved.

**Pull request merged**
