### PR TITLE
fix(#445): validation runs on both initial form and final form

### LINKED ISSUE #445: Bookings created outside of the bookable window don't return an error message
## Expected Behavior

When a user attempts to open a booking request for a date too close or too far from the current date, the system will reject the booking with an appropriate error message.

## Current Behavior

When a user attempts to open a booking request for a date too close or too far from the current date, the system rejects the booking with no specific error message.

## Steps to Reproduce

1. Begin creating a booking
2. Set the booking to one day later (or more than two weeks later, depends on the room)
3. Fill out the rest of the booking form correctly
4. The appearing error message is just "could not submit booking"

## Context (Environment)

# Bug Submission Checklist
- [x] Replication steps
- [ ] Screenshots
- [ ] Tagged commits fixing the bug for traceability
- [ ] Tagged commits updating tests to cover the reported bug	
- [ ] (optional) tagged with “performance” label if performance related

### PR DESCRIPTION
**Pull request by EvanDime**
##### _What existing problem does the pull request solve?_
initial date selection now has working validation and the final booking request creation reuses it to make sure they are still valid. 

### Test plan (required)
Tests now check for proper attribute title as well as bookings now use reservation functions so the old tests are able to be reused. 

##### _List all issues this PR resolves_
- closes #445

##### _Complete these items before requesting reviews_
- [x] Static Analysis Rules Validated
- [x] All commits follow naming conventions

### Sub-tasks Checklist
- [x] UI Implementation
- [x] UI Test
- [x] Backend Implementation
- [x] Backend Tests
- [x] Integration Tests
- [x] System Tests
- [x] Documentation

### CODE REVIEW

**Review by jonathanp16 — APPROVED** [review]
This looks great. Looks also like the reservationValidate function pulled some logic out of duplicated codeblocks and refactored into a reusable function, could be useful if you marked that part of the commit as a refactor for future reports. Approving because the work done satisfies all the requirements. Good job!

**Comment by jonathanp16** [comment]
Also seems to be 2 codesmells but they're referencing comments and unused variables @EvanDime

**Comment by EvanDime** [comment]
> Also seems to be 2 codesmells but they're referencing comments and unused variables @EvanDime

For the unused variable i don't have a choice as the framework needs to set these variables and i need to access the ones that show up after it. So it needs to be assigned.
As for the comment it's something i want to make sure is the case in the future as i am not completely certain that the code is being used. Having the todo will make it easier to find later on in production.

**Review by Alex-Hayeur — APPROVED** [review]
Looks good, and an excellent way to manage the validation. It's preventing code duplication by giving the validation its own function.

**Pull request merged**
