### PR TITLE
feat(#22): time restrictions for rooms

### LINKED ISSUE #22: Time Restriction per Day
### User story
As a user, I can only set a reservation between the allowed times.

### Narrative
While making a reservation, the only times available to make the reservation should fall within the clients allotted times.

As an administrator, I can set the availability time for a room, (Ex a room can only be booked Monday-Friday  between 8am and 11pm) (Think of it as opening/closing hours of the room) 

### Out of scope
Making sure the times are available or blocked by other reservations.

### Acceptance criteria

| # | Given | When | Then |
|---|-------|------|------|
|1|I am a logged in user and all other restrictions are met|I make a reservation within the allotted times|The system does create the reservation|
|2|I am a logged in user and all other restrictions are met|I try to make a reservation before the allotted times|It is not possible to make the reservation|
|3|I am a logged in user and all other restrictions are met|I try to make a reservation after the allotted times|It is not possible to make the reservation|

### PR DESCRIPTION
**Pull request by alecadub**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**
Please provide enough information so that others can review your pull request:

#22 

Explain the **details** for making this change. What existing problem does the pull request solve?

#22

### Test plan (required)
Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

checks have passed

### Closing issues
List all issues this PR resolves.
- `closes #22 ` 

### Pre-Merge checklist 
Complete these items before requesting reviews
- [x] Static Analysis Rules Validated
- [x] All commits follow naming conventions 

### Sub-tasks Checklist
- [x] UI Implementation
- [x] UI Test
- [x] Backend Implementation
- [x] Backend Tests
- [x] Integration Tests
- [x] System Tests
- [x] Documentation

### CODE REVIEW

**Review by danseremet — APPROVED** [review]
👌

**Review by EvanDime — APPROVED** [review]
Very well done. I like the proper use of model functions.

**Review by EvanDime — APPROVED** [review]
Everything still looks good. I am not sure what changes were made with the force push, but everything seems to be in order.

**Comment by alecadub** [comment]
@EvanDime yeah I just had to resolve a few conflicts created from merging pr #269 ^^ @danseremet can you re-approve?

**Review by danseremet — APPROVED** [review]

**Pull request merged**
