### PR TITLE
fix(#252): dusk test for multi date booking

### PR DESCRIPTION
**Pull request by EvanDime**
##### **_IMPORTANT: Always create an issue before a PR and provide enough information so that others can review_**

adds a dusk test to see if we can make a booking with multiple dates 
##### _List all issues this PR resolves_
- applies to  #252

##### _Complete these items before requesting reviews_
- [x] Static Analysis Rules Validated
- [x] All commits follow naming conventions

### CODE REVIEW

**Review by Alex-Hayeur — DISMISSED** [review]

**Comment by EvanDime** [comment]
DO not merge this until i rework it after @alexstojda 's changes for multiple dates

**Review by Alex-Hayeur — APPROVED** [review]
Solid test and also thanks for updating the older test so it still works.

**Review by a-drew — DISMISSED** [review]
test is passing, lgtm

**Review by a-drew — APPROVED** [review]
yes

**Review by Alex-Hayeur — APPROVED** [review]
re-approving after rebase

**Pull request merged**
