### PR TITLE
feat(#333): Added the proper CSU logo and the footer to the login

### LINKED ISSUE #33: Create Roles
### User story
As an administrator, I am able to create roles.

### Narrative
As an administrator, I want to create roles to encompass a set of permissions so that user access to parts of the application can be controlled.

### Out of scope
The actual assignment of users and permissions to roles.

### Acceptance criteria

| # | Given | When | Then |
|---|-------|------|------|
|1|I am an administrator|I create a role|The system registers a new role|
|2|I am not an administrator|I try to create a role|The system prevents me from creating roles|

### PR DESCRIPTION
**Pull request by joeyabou**
### Explain the **details** for making this change.
Updated the login page to have the the CSU logo and added the footer component as specified by the stakeholder and the graphics design team. 

### Closing issues
- closes #33

##### _Complete these items before requesting reviews_
- [X] Static Analysis Rules Validated
- [X] All commits follow naming conventions

### Sub-tasks Checklist
- [X] UI Implementation
- [ ] UI Test
- [ ] Backend Implementation
- [ ] Backend Tests
- [ ] Integration Tests
- [ ] System Tests
- [ ] Documentation

### CODE REVIEW

**Comment by alexstojda** [comment]
Is this using the logo statically? Or the logo set in the application settings? IMO it should be th logo in the settings, which we can set the default as the CSU logo. what do you think?

**Comment by joeyabou** [comment]
> Is this using the logo statically? Or the logo set in the application settings? IMO it should be th logo in the settings, which we can set the default as the CSU logo. what do you think?

Yes it is set statically in the login not the settings . I think we shouldnt do that only because if a new user were to join the application he would be met without the logo. Setting the logo in the settings is fine for the rest of the application but we should keep it static in the login for that reason. Let me know what you think.

**Comment by WindOfRussia** [comment]
Looks like this branch is out of date from main. let me update it and we'll check the CI again.

**Review by Alex-Hayeur — APPROVED** [review]
Looks good. And now we can apply that logo in other places of the site too.

**Comment by WindOfRussia** [comment]
> > Is this using the logo statically? Or the logo set in the application settings? IMO it should be th logo in the settings, which we can set the default as the CSU logo. what do you think?
> 
> Yes it is set statically in the login not the settings . I think we shouldnt do that only because if a new user were to join the application he would be met without the logo. Setting the logo in the settings is fine for the rest of the application but we should keep it static in the login for that reason. Let me know what you think.

tbh I think the default logo should be updated to this new file you're pulling and ensure that settings logo overrides it.

**Review by WindOfRussia — APPROVED** [review]
Approach should be reviewed in the future but I'll approve this now because it does indeed satisfy the PR conditions

**Pull request merged**
