### PR TITLE
chore: Add hotjar to staging

### PR DESCRIPTION
**Pull request by alexstojda**
Chore: install Hotjar (#200)

### CODE REVIEW

**Comment by EvanDime** [comment]
Does this chore need an issue attached to it?

**Review by jonathanp16 — APPROVED** [review]
Very useful for recording user data and analysis. Good job

**Comment by alexstojda** [comment]
> Does this chore need an issue attached to it?

Added

**Review by WindOfRussia — APPROVED** [review]
We'll definitely need this to collect user data during usability testing, nice addition.

**Pull request merged**
